// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIO3PoLnl6TJSrnVhT4ZhmgKd6WKgbcA',
    appId: '1:468797129064:web:9b7d8f2cb03818df8fd6dd',
    messagingSenderId: '468797129064',
    projectId: 'uicsparkhacks2026',
    authDomain: 'uicsparkhacks2026.firebaseapp.com',
    storageBucket: 'uicsparkhacks2026.firebasestorage.app',
    measurementId: 'G-PLT9EKXEM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWszFVBvpB7BqcIf-uqz29h7XZ6Ezq1CI',
    appId: '1:468797129064:android:40b1a7a9dbe1aa458fd6dd',
    messagingSenderId: '468797129064',
    projectId: 'uicsparkhacks2026',
    storageBucket: 'uicsparkhacks2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7deRo7IubjoOpcrBPOlibUyB3uL4GRlg',
    appId: '1:468797129064:ios:1c2f31fda6ba713c8fd6dd',
    messagingSenderId: '468797129064',
    projectId: 'uicsparkhacks2026',
    storageBucket: 'uicsparkhacks2026.firebasestorage.app',
    iosClientId: '468797129064-9rqcn90lekmiqu1oirc9id351816lqqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7deRo7IubjoOpcrBPOlibUyB3uL4GRlg',
    appId: '1:468797129064:ios:1c2f31fda6ba713c8fd6dd',
    messagingSenderId: '468797129064',
    projectId: 'uicsparkhacks2026',
    storageBucket: 'uicsparkhacks2026.firebasestorage.app',
    iosClientId: '468797129064-9rqcn90lekmiqu1oirc9id351816lqqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRIO3PoLnl6TJSrnVhT4ZhmgKd6WKgbcA',
    appId: '1:468797129064:web:2239a25b5b83b4428fd6dd',
    messagingSenderId: '468797129064',
    projectId: 'uicsparkhacks2026',
    authDomain: 'uicsparkhacks2026.firebaseapp.com',
    storageBucket: 'uicsparkhacks2026.firebasestorage.app',
    measurementId: 'G-MDM6WLXZ9S',
  );
}
